version: '3.4'
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    user: app:app
    volumes:
      - data:/home/app/data
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    command:
      - --app.document-root=/home/app/data
      - --app.max-upload-size=1GB
      - --app.max-upload-parts=10

volumes:
  data:
